Repository soft310team2/discord-watch-party-bot, pull requests merged in 2023-08, with the labels that each got.

#30 Feat/delete-watchlist
  bot.py
Labels: enhancement

#31 Feat/add to watchlist
  bot.py
Labels: enhancement

#32 Feat/join watchlist
  bot.py
  watchlist.json
Labels: enhancement

#33 Feat/leave-watchlist
  bot.py
  watchlist.json
Labels: enhancement

#34 Feat/view-watchlist-members
  bot.py
Labels: enhancement

#35 Feat/notify-participants
  bot.py
Labels: enhancement

#37 Hotfix/delete-watchlist
  bot.py
Labels: bug

#38 Feat/delete from watchlist
  bot.py
  watchlist_media_commands.py
Labels: enhancement

#48 Add useage instructions to README.md
  README.md
Labels: documentation

#52 Fix typo README.md
  README.md
Labels: documentation

#50 Feat - clear media from a watchlist
  bot.py
Labels: enhancement

#51 Permission restriction options added to commands that edit watchlists
  bot.py
Labels: enhancement

#49 Refactor/remove-command-file
  bot.py
  watchlist_media_commands.py
Labels: enhancement

#55 Refactor/removed some duplicate code and comments
  README.md
  bot.py
  utils.py
Labels: documentation, enhancement
